<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'auth',
    array(
        'action' => 'login',
        'id'     => $this->id,
    )
));
$form->prepare();

if ($this->messages){
    echo '<ul>';
    foreach($this->messages as $message)
    {
        echo '<li>'.$message.'</li>';
    }
    echo '</ul>';
}

?>

    <form role="form" method="POST">
  <div class="form-group">
    <label for="email"><?php echo $this->formLabel($form->get('email')) ?></label>
      <?php echo $this->formInput($form->get('email')) ?>
  </div>
  <div class="form-group">
    <label for="pwd"><?php echo $this->formLabel($form->get('password')) ?></label>
      <?php echo $this->formInput($form->get('password')) ?>
  </div>
  <div class="checkbox">
    <label><input type="checkbox"> Remember me</label>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>

